# coding: utf-8

"""
    Atla Insights API

    Development documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from atla_insights.client._generated_client.models.list_traces200_response import ListTraces200Response

class TestListTraces200Response(unittest.TestCase):
    """ListTraces200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTraces200Response:
        """Test ListTraces200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTraces200Response`
        """
        model = ListTraces200Response()
        if include_optional:
            return ListTraces200Response(
                traces = [
                    _generated_client.models.list_traces_200_response_traces_inner.listTraces_200_response_traces_inner(
                        id = '', 
                        environment = 'PROD', 
                        is_success = True, 
                        is_completed = True, 
                        metadata = {
                            'key' : null
                            }, 
                        started_at = '', 
                        ended_at = '', )
                    ],
                total = 1.337,
                page = 1.337,
                page_size = 1.337
            )
        else:
            return ListTraces200Response(
                traces = [
                    _generated_client.models.list_traces_200_response_traces_inner.listTraces_200_response_traces_inner(
                        id = '', 
                        environment = 'PROD', 
                        is_success = True, 
                        is_completed = True, 
                        metadata = {
                            'key' : null
                            }, 
                        started_at = '', 
                        ended_at = '', )
                    ],
                total = 1.337,
                page = 1.337,
                page_size = 1.337,
        )
        """

    def testListTraces200Response(self):
        """Test ListTraces200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
