# coding: utf-8

"""
    Atla Insights API

    Development documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from atla_insights.client._generated_client.models.list_traces200_response_traces_inner import ListTraces200ResponseTracesInner

class TestListTraces200ResponseTracesInner(unittest.TestCase):
    """ListTraces200ResponseTracesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTraces200ResponseTracesInner:
        """Test ListTraces200ResponseTracesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTraces200ResponseTracesInner`
        """
        model = ListTraces200ResponseTracesInner()
        if include_optional:
            return ListTraces200ResponseTracesInner(
                id = '',
                environment = 'PROD',
                is_success = True,
                is_completed = True,
                metadata = {
                    'key' : ''
                    },
                started_at = '',
                ended_at = ''
            )
        else:
            return ListTraces200ResponseTracesInner(
                id = '',
                environment = 'PROD',
                is_success = True,
                is_completed = True,
                started_at = '',
                ended_at = '',
        )
        """

    def testListTraces200ResponseTracesInner(self):
        """Test ListTraces200ResponseTracesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
