# coding: utf-8

"""
    Atla Insights API

    Development documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from atla_insights.client._generated_client.models.list_traces_metadata_filter_parameter_inner import ListTracesMetadataFilterParameterInner

class TestListTracesMetadataFilterParameterInner(unittest.TestCase):
    """ListTracesMetadataFilterParameterInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTracesMetadataFilterParameterInner:
        """Test ListTracesMetadataFilterParameterInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTracesMetadataFilterParameterInner`
        """
        model = ListTracesMetadataFilterParameterInner()
        if include_optional:
            return ListTracesMetadataFilterParameterInner(
                key = '',
                value = ''
            )
        else:
            return ListTracesMetadataFilterParameterInner(
                key = '',
                value = '',
        )
        """

    def testListTracesMetadataFilterParameterInner(self):
        """Test ListTracesMetadataFilterParameterInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
