# coding: utf-8

"""
    Atla Insights API

    Development documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from atla_insights.client._generated_client.models.get_traces_by_ids200_response_traces_inner_custom_metric_values_inner import GetTracesByIds200ResponseTracesInnerCustomMetricValuesInner

class TestGetTracesByIds200ResponseTracesInnerCustomMetricValuesInner(unittest.TestCase):
    """GetTracesByIds200ResponseTracesInnerCustomMetricValuesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTracesByIds200ResponseTracesInnerCustomMetricValuesInner:
        """Test GetTracesByIds200ResponseTracesInnerCustomMetricValuesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTracesByIds200ResponseTracesInnerCustomMetricValuesInner`
        """
        model = GetTracesByIds200ResponseTracesInnerCustomMetricValuesInner()
        if include_optional:
            return GetTracesByIds200ResponseTracesInnerCustomMetricValuesInner(
                id = '',
                trace_id = '',
                custom_metric_id = '',
                value = '',
                custom_metric = _generated_client.models.get_traces_by_ids_200_response_traces_inner_custom_metric_values_inner_custom_metric.getTracesByIds_200_response_traces_inner_customMetricValues_inner_customMetric(
                    id = '', 
                    name = '', 
                    data_type = 'BOOLEAN', )
            )
        else:
            return GetTracesByIds200ResponseTracesInnerCustomMetricValuesInner(
                id = '',
                trace_id = '',
                custom_metric_id = '',
                value = '',
        )
        """

    def testGetTracesByIds200ResponseTracesInnerCustomMetricValuesInner(self):
        """Test GetTracesByIds200ResponseTracesInnerCustomMetricValuesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
